apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: productcatalog
  namespace: argocd
spec:
  project: otel-demo

  source:
    repoURL: https://github.com/robertteah/visionlens-devops-project-demo.git
    targetRevision: main
    path: kubernetes/productcatalog

  destination:
    server: https://kubernetes.default.svc
    namespace: otel-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
